<!DOCTYPE html>
<html>
<head>
	<title>LOGIN</title>
	<link rel="stylesheet" type="text/css" href="styles/cssjoin.css" />
</head>
<body>
	<header>
		<ul>
			<li><a href="HOME.php">home</a></li>
			<li><a href="join_pedagang.php">jadi seller</a></li>
		</ul>
	</header>
	<form action="TOKO.PHP" method="POST">

		<h1>login</h1>
		usernanme<br>
		<input type="text" name="usernanme"><br>
		password<br>
		<input type="password" name="password"><br><br>
		<input type="submit" name="login" value="login">

	</form>

</body>
</html>